### ISSUE TITLE
文档描述错误

### ISSUE THREAD

**Issue by tian-y-x** [MrXiaoM/mirai-docs#11]

**Comment by MrXiaoM** [comment]
¿

**Comment by tian-y-x** [comment]
https://wiki.mrxiaom.top/zh/mirai/%E5%BC%80%E5%8F%91%E5%85%A5%E9%97%A8_%E9%83%A8%E7%BD%B2%E5%BC%80%E5%8F%91%E7%8E%AF%E5%A2%83

>在 Java 要新建一个无参数的构造函数并在里面填入插件描述，必须要无参数的构造函数，并使用公开静态字段将其实例化，使其成为与 Kotlin 类似的单例类。
>
>```
>// java
>public class ExamplePluginMain extends JavaPlugin {
>    public static final ExamplePluginMain INSTANCE = new ExamplePluginMain();
>    public ExamplePluginMain() {
>        super(new JvmPluginDescriptionBuilder(
>            // 插件ID
>            "org.example.mirai.plugin",
>            // 版本
>            "1.0.0"
>        )
>        // 插件名
>        .name("示例插件")
>        // 作者
>        .author("MrXiaoM")
>        // 描述
>        .info("An example plugin for tutorial")
>        .build());
>    }
>}
>```
>
>

这里按我的理解，`ExamplePluginMain` 类设为单例时，构造方法应为私有。

**Comment by MrXiaoM** [comment]
确实
