### ISSUE TITLE
不推荐直接使用公共事件通道 公共事件通道 GlobalEventChannel

### ISSUE THREAD

**Issue by cssxsh** [MrXiaoM/mirai-docs#6]
https://github.com/MrXiaoM/mirai-docs/blob/main/docs/dev.md#%E8%8E%B7%E5%8F%96%E4%BA%8B%E4%BB%B6%E9%80%9A%E9%81%93

最好使用 CoroutineScope.globalEventChannel （GlobalEventChannel.parentScope）
套一层 自定义的 CoroutineScope

1. 可以在 CoroutineScope 添加 exceptionHandler 记录 意外的 throw 
2. 可以单独对下游的 EventChannel 进行控制 （JvmPlugin 也是 CoroutineScope  实现，可以用 JvmPlugin.globalEventChannel 直接获得专属的 EventChannel ，自带 exceptionHandler ）
3. 直接使用  GlobalEventChannel 。无法从从外部中止(直接停止协程), 需要操作 Listener

**Comment by MrXiaoM** [comment]
az其实这个文档我打算重写并把这个仓库存档了，因为我自己看起来都太乱了

**Comment by MrXiaoM** [comment]
不过还是感谢你的一系列指正，我会在新文档编写时注意
